# Generated by Django 5.2.7 on 2025-10-16 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_reservation_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'. Maximum 15 chiffres.", regex='^\\+?1?\\d{9,15}$')])),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('delivery_address', models.CharField(max_length=200)),
                ('payment_method', models.CharField(default='card', max_length=50)),
                ('purchase_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='home.purchase')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehicle')),
            ],
        ),
    ]
