# Generated by Django 5.2.7 on 2025-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_purchase_purchasevehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('transfer', 'Virement bancaire'), ('cash', 'Espèces')], default='card', max_length=50),
        ),
    ]
